#!/bin/bash
### BEGIN INIT INFO
# Provides:          first_boot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Generates new ssh host keys on first boot & makes swap
# Description:       Generates new ssh host keys on first boot & makes swap
### END INIT INFO

# Generate SSH keys & enable SSH
[ -f /etc/ssh/ssh_host_rsa_key ] || /usr/bin/ssh-keygen -f /etc/ssh/ssh_host_rsa_key -t rsa -N ""
[ -f /etc/ssh/ssh_host_ed25519_key] || /usr/bin/ssh-keygen -f /etc/ssh/ssh_host_ed25519_key -t ed25519 -N ""
[ -f /etc/ssh/ssh_host_ecdsa_key ] || /usr/bin/ssh-keygen -f /etc/ssh/ssh_host_ecdsa_key -t ecdsa -N ""
/usr/sbin/service ssh start
/usr/sbin/update-rc.d ssh defaults

echo -e "w\nq" | /sbin/fdisk /dev/sda

/sbin/mkswap /.swapfile
/sbin/swapon /.swapfile

cat << SWAPENTRY >> /etc/fstab
/.swapfile      none            swap    sw                              0       0
SWAPENTRY

# Spin-down HDDs after 10 Minutes + 15 Seconds
cat << HDPARMENTRY >> /etc/hdparm.conf
/dev/sda {
	spindown_time = 123
}

/dev/sdb {
	spindown_time = 123
}
HDPARMENTRY

/usr/sbin/update-rc.d first_boot remove
rm -f $0
